var u={
    Name:"Rudhra",
    Age:21,
    Group:"MJI2"
};
for (var i in u){
    console.log(i,u[i]);
    
document.write(i,u[i]);
}

var surya={
    Name:"T.JAYASURYA",
    DOB: "20.11.2001",
    E_mail: "t.jayasurya2001b.com@gmail.com",
    Address: "poonamallee Chennai-56",
    Phone:9840500620,
    Education:"B.COM",
    Skills:"programmer",
    Language_Known: "Tamil,English",
    Gender: "Male",
    Hobbies: "Gaming,Listening Music",

};
console.log(JSON.stringify(surya));

document.write(JSON.stringify(surya));
